#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-PerfCounter
version:      0.02
version_from: PerfCounter.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
